version: '3.9'
services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:latest
    ports:
      - "8161:8161"
    volumes:
      - ./activemq:/opt/apache-activemq-5.15.6
    environment:
      - ACTIVEMQ_OPTS=-Xms1024m -Xmx2048m
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
  java_hardware_order:
    container_name: java_hardware_order
    build: ./java_hardware_order/
  java_smartphone_app:
    container_name: java_smartphone_app
    build: ./java_smartphone_app
  javascript_software_order:
    container_name: javascript_software_order
    build: ./javascript_software_order
  javascript_website:
    container_name: javascript_website
    build: ./javascript_website